#define INTBOUTS 0
#define INTINCELEC 1
#define INTNONBONDCUT 2
#define INTEVALFLAG 3
#define INTSIZE 4

#define FLOATINFO 0
#define FLOATSCALE14 1
#define FLOATUNBOUNDINTERNAL 2
#define FLOATSIZE 3

